version: "3.2"

services:
  pg_go:
    image: postgres:12.4
    container_name: pg_go
    restart: unless-stopped
    environment:
      POSTGRES_USER: gorood
      POSTGRES_PASSWORD: gopassword
      POSTGRES_DB: pg_go
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    networks:
      - default