version: "3.8"

services:
  pg_go:
    image: postgres:12.4
    container_name: pg_go
    restart: unless-stopped
    environment:
      POSTGRES_USER: go_rood
      POSTGRES_PASSWORD: go_password
      POSTGRES_DB: pg_go
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
